name: lomap-env
channels:
  - conda-forge
dependencies:
  - networkx
  - numpy
  - matplotlib
  # https://github.com/rdkit/rdkit/issues/9335
  - rdkit != 2024.03.4, != 2026.03.3
  - pytest
  - pytest-xdist
  - codecov
