name: lomap-docs
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- python=3.11
- gufe>=1.6.1
# Last compatible sphinx release compatible with sphinx-toolbox is v8.2.3
- sphinx <=7.2.6
- sphinx-toolbox
- pip:
  - sphinx-design
  - sphinx-toolbox
  - git+https://github.com/OpenFreeEnergy/ofe-sphinx-theme@v0.3.1
